# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Default repository filters and implicit-tool stop words for SHERLOC."""

DEFAULT_FILE_EXTENSIONS = ("py", "cfg")

DEFAULT_EXCLUDE_DIRS = (
    "test",
    "tests",
    "testing",
    "test_",
    "_test",
    "__pycache__",
    ".git",
    ".github",
    "docs",
    "examples",
    "scripts",
    "tools",
    "venv",
    "env",
    "node_modules",
    "dist",
    "build",
    "target",
    "bin",
    "obj",
    "coverage",
    ".pytest_cache",
    ".tox",
    ".mypy_cache",
    "locale",
    "translations",
    "i18n",
    "l10n",
    "static",
    "assets",
    "media",
    "uploads",
    "logs",
    "tmp",
    "temp",
    "vendor",
    "libs",
    "dependencies",
    "settings",
    "local_settings",
    "fixtures",
    "data",
    "datasets",
    "notebooks",
    "jupyter",
    "ipynb_checkpoints",
    "deploy",
    "deployment",
    "docker",
    "kubernetes",
    "ci",
    "cd",
    "github",
    "gitlab",
    "bitbucket",
    "readme",
    "license",
    "changelog",
    "contributing",
)

DEFAULT_COMMON_WORDS_FILTER = (
    "the",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "can",
    "this",
    "that",
    "these",
    "those",
    "a",
    "an",
    "as",
    "if",
    "then",
    "else",
    "when",
    "where",
    "why",
    "how",
    "what",
    "which",
    "who",
    "whom",
    "whose",
    "need",
    "find",
    "search",
    "look",
    "function",
    "class",
    "method",
    "variable",
    "query",
)
