# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Parsing of agent responses in the SHERLOC localization loop.

Every assistant turn is expected to carry either a ``<tool_call>`` block that
requests more evidence from the repository, or a ``<locations>`` block that
submits the suspected edit locations. A sibling ``<findings>`` block, when
present, is the free-form diagnosis stored alongside those locations. Models deviate from that contract in
recurring ways, so the parser also recovers unclosed tags, XML-wrapped tool
names, CDATA sections, Python ``dict`` reprs, and bare JSON emitted after a
``</think>`` block. Recovering a malformed response keeps a trajectory alive
instead of ending it on a formatting slip, and every recovery path is logged so
that its frequency can be measured.

Parsing here is purely textual; token accounting lives in ``context_manager``.
"""

import json
import logging
import re
from typing import Dict

from nemo_skills.utils import get_logger_name

LOG = logging.getLogger(get_logger_name(__file__))


class DialogProcessor:
    """Processes dialog output to extract tool calls and locations."""

    @staticmethod
    def extract_response(dialog_text: str, config=None):
        """Parse one assistant response into a tool call or a location submission.

        Args:
            dialog_text: Raw text generated by the model for a single turn
            config: Generation config. ``enable_implicit_tool_detection`` decides
                whether responses without explicit tags are salvaged, and
                ``file_extensions`` and ``common_words_filter`` tune that salvage

        Returns:
            ``{"type": "tool_calls", "tool_call": {...}}`` for a tool call,
            ``{"type": "locations", "locations": [...], "findings": ...}`` for a
            submission (``findings`` is the ``<findings>`` block text, or ``None``
            when that block is absent), or ``None`` when nothing could be recovered.
        """
        # First check if this is a Python dict representation (single quotes)
        # This handles cases like: {'type': 'locations', 'locations': '...'}
        if dialog_text.strip().startswith("{") and dialog_text.strip().endswith("}"):
            extracted = DialogProcessor._extract_python_dict(dialog_text)
            if extracted:
                return extracted

        # Standard tag-based extraction
        if "<tool_call>" in dialog_text:
            LOG.info("Found <tool_call> block in output")
            return DialogProcessor._extract_tool_calls(dialog_text)
        elif "<locations>" in dialog_text:
            LOG.info("Found <locations> block in output")
            return DialogProcessor._extract_locations(dialog_text)
        else:
            # Check if implicit tool detection is enabled
            enable_implicit = getattr(config, "enable_implicit_tool_detection", True) if config else True
            if enable_implicit:
                LOG.warning("No <tool_call> or <locations> found, checking for implicit tool calls")
                return DialogProcessor._extract_implicit_tool_calls(dialog_text, config)
            else:
                LOG.warning("No <tool_call> or <locations> found, and implicit tool detection is disabled")
                return None

    @staticmethod
    def _extract_tool_calls(dialog_text: str) -> Dict:
        """Extract tool calls from dialog text with unified handling of various formats.

        Supports:
        1. Standard format: <tool_call>{...}</tool_call>
        2. Unclosed tags: <tool_call>{...
        3. Malformed JSON with extra braces
        4. Two JSON formats:
           - Format 1: {"tool": "view_file", "path": "...", ...}
           - Format 2: {"tool_name": {...params...}}
        5. XML tool name: <tool_call><view_file>{...}</view_file></tool_call>
        6. CDATA wrapper: <tool_call><![CDATA[{...}]]></tool_call>
        """

        # Step 1: Extract raw content between tags (or after unclosed tag)
        raw_content = DialogProcessor._extract_tag_content(dialog_text, "tool_call")
        if not raw_content:
            return None

        # Step 1.5: Handle XML-style tool names inside <tool_call>
        # e.g. <view_file>{"path": "..."}</view_file> or <view_file>{"path": "..."}</view_call>
        if raw_content.lstrip().startswith("<"):
            xml_result = DialogProcessor._parse_xml_tool_call(raw_content)
            if xml_result:
                return xml_result

        # Step 2: Parse JSON with error recovery
        tool_data = DialogProcessor._parse_json_with_recovery(raw_content, "tool_call")
        if not tool_data:
            return None

        # Step 3: Normalize to unified format
        return DialogProcessor._normalize_tool_format(tool_data)

    @staticmethod
    def _parse_xml_tool_call(content: str) -> Dict:
        """Parse XML-style tool calls like <view_file>{"path": "..."}</view_file>.

        Also handles CDATA wrappers and mismatched closing tags (e.g. </view_call>).
        """
        content = content.strip()

        # Handle CDATA: <![CDATA[{...}]]>
        cdata_match = re.search(r"<!\[CDATA\[(.*?)\]\]>", content, re.DOTALL)
        if cdata_match:
            json_str = cdata_match.group(1).strip()
            try:
                tool_data = json.loads(json_str)
                LOG.info("Parsed CDATA tool call")
                return DialogProcessor._normalize_tool_format(tool_data)
            except json.JSONDecodeError:
                pass

        # Handle <tool_name>{json}</tool_name> or <tool_name>{json}</anything>
        tag_match = re.match(r"<(\w+)>\s*(.*)", content, re.DOTALL)
        if not tag_match:
            return None

        tool_name = tag_match.group(1)
        rest = tag_match.group(2).strip()

        known_tools = {"view_file", "codebase_search", "connected_tree", "repo_tree"}

        # Handle <name>tool_name</name><path>value</path> format
        if tool_name == "name":
            name_match = re.match(r"(\w+)</name>\s*(.*)", rest, re.DOTALL)
            if name_match:
                tool_name = name_match.group(1)
                rest = name_match.group(2).strip()
                # Parse XML-style params: <path>value</path><view_range>[1,50]</view_range>
                params = {}
                for param_match in re.finditer(r"<(\w+)>(.*?)</\1>", rest, re.DOTALL):
                    key = param_match.group(1)
                    val = param_match.group(2).strip()
                    try:
                        val = json.loads(val)
                    except (json.JSONDecodeError, ValueError):
                        pass
                    params[key] = val
                if params or tool_name in ("repo_tree", "connected_tree"):
                    tool_call = {"tool": tool_name, **params}
                    LOG.info(f"Parsed <name> XML tool call: {tool_name}")
                    return {"type": "tool_calls", "tool_call": tool_call}

        if tool_name not in known_tools:
            return None

        # Extract JSON from the remaining content
        json_match = re.search(r"\{.*\}", rest, re.DOTALL)
        if json_match:
            try:
                params = json.loads(json_match.group(0))
                tool_call = {"tool": tool_name, **params}
                LOG.info(f"Parsed XML-style tool call: {tool_name}")
                return {"type": "tool_calls", "tool_call": tool_call}
            except json.JSONDecodeError:
                pass

        # repo_tree and connected_tree can have empty params
        if tool_name in ("repo_tree", "connected_tree") and "{" not in rest:
            LOG.info(f"Parsed XML-style tool call with no params: {tool_name}")
            return {"type": "tool_calls", "tool_call": {"tool": tool_name}}

        return None

    @staticmethod
    def _extract_tag_content(text: str, tag_name: str) -> str:
        """Extract content from XML-style tags with fallback for unclosed tags."""
        # Try properly closed tag first
        pattern = f"<{tag_name}>(.*?)</{tag_name}>"
        match = re.search(pattern, text, re.DOTALL)

        if match:
            return match.group(1).strip()

        # Fallback: unclosed tag - extract everything after the tag
        pattern = f"<{tag_name}>\\s*(.*?)$"
        match = re.search(pattern, text, re.DOTALL)

        if match:
            LOG.warning(f"Detected unclosed <{tag_name}> tag")
            return match.group(1).strip()

        return None

    @staticmethod
    def _parse_json_with_recovery(json_str: str, context: str = "") -> dict:
        """Parse JSON with recovery strategies for common issues."""
        if not json_str:
            return None

        LOG.debug(f"Attempting to parse JSON for {context} (first 200 chars): {json_str[:200]}...")

        # Strategy 1: Parse as-is
        try:
            data = json.loads(json_str)
            LOG.debug(f"Successfully parsed JSON as-is for {context}")
            return data
        except json.JSONDecodeError as e:
            LOG.debug(f"Initial parse failed for {context}: {e}")

        # Strategy 2: Find complete JSON by brace matching
        complete_json = DialogProcessor._extract_complete_json(json_str)
        if complete_json and complete_json != json_str:
            try:
                data = json.loads(complete_json)
                LOG.debug(f"Successfully parsed after brace matching for {context}")
                return data
            except json.JSONDecodeError as e:
                LOG.debug(f"Brace-matched parse failed for {context}: {e}")

        # Strategy 3: Common fixes
        # Fix extra closing braces (e.g., }})
        if json_str.rstrip().endswith("}}") and json_str.count("}") > json_str.count("{"):
            fixed = json_str.rstrip()[:-1]
            try:
                data = json.loads(fixed)
                LOG.debug(f"Successfully parsed after removing extra brace for {context}")
                return data
            except json.JSONDecodeError:
                pass

        # Fix trailing content after last valid }
        last_brace = json_str.rfind("}")
        if last_brace > 0 and last_brace < len(json_str) - 1:
            trimmed = json_str[: last_brace + 1]
            try:
                data = json.loads(trimmed)
                LOG.debug(f"Successfully parsed after trimming trailing content for {context}")
                return data
            except json.JSONDecodeError:
                pass

        LOG.warning(f"All JSON parsing attempts failed for {context}")
        return None

    @staticmethod
    def _extract_complete_json(text: str) -> str:
        """Extract complete JSON object by matching braces, handling strings properly."""
        if not text or not text.strip().startswith("{"):
            return None

        brace_count = 0
        in_string = False
        escape_next = False

        for i, char in enumerate(text):
            if escape_next:
                escape_next = False
                continue

            if char == "\\" and in_string:
                escape_next = True
                continue

            if char == '"' and not escape_next:
                in_string = not in_string
                continue

            if not in_string:
                if char == "{":
                    brace_count += 1
                elif char == "}":
                    brace_count -= 1
                    if brace_count == 0:
                        return text[: i + 1]

        return None

    @staticmethod
    def _normalize_tool_format(tool_data: dict) -> dict:
        """Normalize different tool formats to a unified structure."""
        if not isinstance(tool_data, dict):
            LOG.warning(f"Tool data is not a dictionary: {type(tool_data)}")
            return None

        # Format 1: {"tool": "view_file", "path": "...", ...}
        # Already in the target format; wrap it as-is.
        if "tool" in tool_data:
            LOG.debug("Detected Format 1 tool call (with 'tool' key)")
            return {"type": "tool_calls", "tool_call": tool_data}

        # Format 2: {"tool_name": {...params...}}
        # Need to flatten this structure
        tool_names = list(tool_data.keys())
        if len(tool_names) == 1:
            tool_name = tool_names[0]
            params = tool_data[tool_name]

            if isinstance(params, dict):
                # Merge tool name with parameters
                unified_tool_call = {"tool": tool_name, **params}
                LOG.debug(f"Detected Format 2 tool call, normalized to: {unified_tool_call}")
                return {"type": "tool_calls", "tool_call": unified_tool_call}
            else:
                LOG.warning(f"Tool parameters are not a dictionary for tool '{tool_name}': {type(params)}")

        LOG.warning(f"Unrecognized tool format with keys: {list(tool_data.keys())}")
        return None

    @staticmethod
    def _extract_python_dict(dialog_text: str) -> Dict:
        """Extract response from Python dict representation (with single quotes).

        Handles cases like:
        {'type': 'locations', 'locations': 'file1.py:L10-L20\\nfile2.py:L30-L40'}
        """
        try:
            # Use ast.literal_eval to safely parse Python literals
            import ast

            data = ast.literal_eval(dialog_text.strip())

            if not isinstance(data, dict):
                return None

            LOG.debug(f"Successfully parsed Python dict: {data}")

            # Handle different response types
            if data.get("type") == "locations":
                # Parse the locations string if it's a string
                locations = data.get("locations", "")
                if isinstance(locations, str):
                    # Parse location strings into structured format
                    parsed_locations = []
                    for line in locations.split("\n"):
                        line = line.strip()
                        if line:
                            location_match = re.match(r"([^:]+):L(\d+)-L(\d+)", line)
                            if location_match:
                                file_path, start_line, end_line = location_match.groups()
                                parsed_locations.append(
                                    {
                                        "file_path": file_path,
                                        "start_line": int(start_line),
                                        "end_line": int(end_line),
                                        "raw": line,
                                    }
                                )

                    return {
                        "type": "locations",
                        "locations": parsed_locations,
                        "findings": data.get("findings"),
                    }
                else:
                    # Already structured
                    data.setdefault("findings", None)
                    return data

            elif data.get("type") == "tool_calls":
                # Already in correct format
                return data

            # Try to interpret as a tool call
            elif "tool" in data or len(data) == 1:
                return DialogProcessor._normalize_tool_format(data)

        except (ValueError, SyntaxError) as e:
            LOG.debug(f"Failed to parse as Python dict: {e}")

        return None

    @staticmethod
    def _extract_locations(dialog_text: str) -> Dict:
        """Extract the submitted edit locations from a ``<locations>`` block.

        Both ``path:L<start>-L<end>`` ranges and single ``path:L<line>``
        references are accepted. A line matching neither form is preserved
        verbatim under the ``raw`` key rather than dropped.
        """
        # Use unified tag extraction
        locations_text = DialogProcessor._extract_tag_content(dialog_text, "locations")
        if not locations_text:
            return {
                "type": "locations",
                "locations": [],
                "findings": DialogProcessor.extract_findings(dialog_text),
            }

        # Parse location lines
        locations = []
        for line in locations_text.split("\n"):
            line = line.strip()
            if line and not line.startswith("#"):
                # Try to match range format first: file:L<start>-L<end>
                location_match = re.match(r"([^:]+):L(\d+)-L(\d+)", line)
                if location_match:
                    file_path, start_line, end_line = location_match.groups()
                    locations.append(
                        {"file_path": file_path, "start_line": int(start_line), "end_line": int(end_line), "raw": line}
                    )
                else:
                    # Try to match single line format: file:L<line>
                    single_line_match = re.match(r"([^:]+):L(\d+)", line)
                    if single_line_match:
                        file_path, line_num = single_line_match.groups()
                        locations.append(
                            {
                                "file_path": file_path,
                                "start_line": int(line_num),
                                "end_line": int(line_num),  # Same as start for single line
                                "raw": line,
                            }
                        )
                    else:
                        locations.append({"raw": line})

        return {
            "type": "locations",
            "locations": locations,
            "findings": DialogProcessor.extract_findings(dialog_text),
        }

    @staticmethod
    def extract_findings(dialog_text: str) -> str | None:
        """Return the text of a ``<findings>`` block, or ``None`` if there is none.

        The block is free-form diagnosis meant for a downstream repair agent.
        Unclosed tags are recovered the same way as ``<locations>``.
        """
        findings_text = DialogProcessor._extract_tag_content(dialog_text, "findings")
        if not findings_text:
            return None
        return findings_text

    @staticmethod
    def _extract_implicit_tool_calls(dialog_text: str, config=None) -> Dict:
        """Extract tool calls that appear as JSON without <tool_call> wrapper."""
        # Check for JSON after </think> tag
        if "</think>" in dialog_text:
            # Split and clean up the text after </think>
            after_think = dialog_text.split("</think>")[1].strip()
            # Replace escaped newlines and multiple newlines with a single space
            after_think = re.sub(r"\\n|\n+", " ", after_think)

            # First try: Look for any JSON-like structure with a path field
            json_pattern = r"\{(?:[^{}]|\"[^\"]*\")*\"path\"(?:[^{}]|\"[^\"]*\")*\}"
            json_match = re.search(json_pattern, after_think)

            if json_match:
                try:
                    json_str = json_match.group(0)
                    # Clean up any remaining escapes or whitespace
                    json_str = json_str.replace("\\", "")
                    tool_data = json.loads(json_str)

                    # This pattern requires a path, so it always represents a file view.
                    tool_data["tool"] = "view_file"
                    tool_data.setdefault("view_range", None)
                    LOG.info(f"Found JSON tool call after </think>: {tool_data}")
                    return {"type": "tool_calls", "tool_call": tool_data}
                except json.JSONDecodeError as e:
                    LOG.warning(f"Failed to parse JSON after </think>: {e}")

            # Second try: Simple file path request
            # Look for quoted or unquoted file paths after </think>
            file_extensions = getattr(config, "file_extensions", None) if config else None
            if file_extensions:
                # Create pattern from configured file extensions
                extensions_pattern = "|".join(re.escape(ext) for ext in file_extensions)
                file_path_pattern = rf'(?:\'|")?([^\'"\s]+?\.(?:{extensions_pattern}))(?:\'|")?'
            else:
                # Fallback to default extensions if none provided
                file_path_pattern = r'(?:\'|")?([^\'"\s]+?\.(?:py|cpp|h|hpp|java|js|ts|rb|go|rs|cs|php))(?:\'|")?'

            file_path_match = re.search(file_path_pattern, after_think)
            if file_path_match:
                tool_data = {
                    "tool": "view_file",
                    "path": file_path_match.group(1),
                    "view_range": None,
                }
                LOG.info(f"Found simple file path request: {tool_data['path']}")
                return {"type": "tool_calls", "tool_call": tool_data}

            # Third try: Simple search query request
            # Look for quoted or unquoted search terms after </think>
            # Common patterns: "search for X", "find X", "look for X", "X function", "X class"
            search_patterns = [
                r'search\s+for\s+(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)(?:\'|")?',
                r'find\s+(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)(?:\'|")?',
                r'look\s+for\s+(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)(?:\'|")?',
                r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+function(?:\'|")?',
                r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+class(?:\'|")?',
                r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+method(?:\'|")?',
                r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+variable(?:\'|")?',
            ]

            for pattern in search_patterns:
                search_match = re.search(pattern, after_think, re.IGNORECASE)
                if search_match:
                    search_term = search_match.group(1).strip()
                    # Clean up the search term
                    search_term = re.sub(r'[\'"]', "", search_term)
                    if search_term and len(search_term) > 1:  # Ensure it's not just whitespace
                        tool_data = {
                            "tool": "codebase_search",
                            "query": search_term,
                        }
                        LOG.info(f"Found simple search request: {tool_data['query']}")
                        return {"type": "tool_calls", "tool_call": tool_data}

        # Look for specific tool call patterns
        # View tool: {"path": "...", "view_range": [...]}
        view_pattern = r'\{[^{}]*"path"[^{}]*(?:"view_range"[^{}]*)?}'
        # Repo tree tool: {} or {"repo_tree": true} or similar
        repo_tree_pattern = r'\{[^{}]*"repo_tree"[^{}]*\}'
        # Codebase search tool: {"query": "..."}
        codebase_search_pattern = r'\{[^{}]*"query"[^{}]*\}'

        # Try view tool first
        json_match = re.search(view_pattern, dialog_text)
        if json_match:
            try:
                tool_data = json.loads(json_match.group())
                tool_data["tool"] = "view_file"
                LOG.warning(f"Found implicit view tool call: {tool_data}")
                return {"type": "tool_calls", "tool_call": tool_data}
            except json.JSONDecodeError as e:
                LOG.warning(f"Failed to parse implicit view tool call JSON: {e}")

        # Try codebase search tool
        json_match = re.search(codebase_search_pattern, dialog_text)
        if json_match:
            try:
                tool_data = json.loads(json_match.group())
                tool_data["tool"] = "codebase_search"
                # Check if query is empty or whitespace
                if not tool_data.get("query", "").strip():
                    LOG.warning("Empty query in codebase_search tool call")
                else:
                    LOG.info(f"Found implicit codebase_search tool call: {tool_data}")
                    return {"type": "tool_calls", "tool_call": tool_data}
            except json.JSONDecodeError as e:
                LOG.warning(f"Failed to parse implicit codebase_search tool call JSON: {e}")

        # Try repo tree tool
        json_match = re.search(repo_tree_pattern, dialog_text)
        if json_match:
            try:
                tool_data = json.loads(json_match.group())
                tool_data["tool"] = "repo_tree"
                LOG.info(f"Found implicit repo_tree tool call: {tool_data}")
                return {"type": "tool_calls", "tool_call": tool_data}
            except json.JSONDecodeError as e:
                LOG.warning(f"Failed to parse implicit repo_tree tool call JSON: {e}")

        # Try simple search query detection in general dialog text
        # Look for common search patterns throughout the dialog
        search_patterns_general = [
            r'search\s+for\s+(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)(?:\'|")?',
            r'find\s+(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)(?:\'|")?',
            r'look\s+for\s+(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)(?:\'|")?',
            r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+function(?:\'|")?',
            r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+class(?:\'|")?',
            r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+method(?:\'|")?',
            r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*)\s+variable(?:\'|")?',
            # Also look for standalone terms that might be function/class names
            r'(?:\'|")?([A-Za-z_][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)(?:\'|")?',  # CamelCase
            r'(?:\'|")?([a-z_][a-z0-9_]*)(?:\'|")?',  # snake_case
            # Specific pattern for quoted identifiers
            r'["\']([A-Za-z_][A-Za-z0-9_]*[A-Za-z0-9_]*)["\']',  # Quoted identifiers
        ]

        for pattern in search_patterns_general:
            search_match = re.search(pattern, dialog_text, re.IGNORECASE)
            if search_match:
                search_term = search_match.group(1).strip()
                # Clean up the search term
                search_term = re.sub(r'[\'"]', "", search_term)
                # Filter out common words that shouldn't be searched
                common_words_list = getattr(config, "common_words_filter", None) if config else None
                common_words = set(common_words_list) if common_words_list else set()
                if (
                    search_term
                    and len(search_term) > 2  # Ensure it's not just a short word
                    and search_term.lower() not in common_words
                    and not search_term.isdigit()
                ):  # Don't search for pure numbers
                    tool_data = {
                        "tool": "codebase_search",
                        "query": search_term,
                    }
                    LOG.info(f"Found implicit search request: {tool_data['query']}")
                    return {"type": "tool_calls", "tool_call": tool_data}

        # Check for empty JSON object (repo_tree tool)
        empty_json_match = re.search(r"^\s*\{\s*\}\s*$", dialog_text.strip())
        if empty_json_match:
            tool_data = {"tool": "repo_tree"}
            LOG.info(f"Found implicit empty repo_tree tool call: {tool_data}")
            return {"type": "tool_calls", "tool_call": tool_data}

        # Last resort: Check for dictionary format: {'type': 'tool_calls', 'tool_call': {...}}
        dict_pattern = r"\{'type':\s*'tool_calls',\s*'tool_call':\s*\{[^}]+\}\}"
        dict_match = re.search(dict_pattern, dialog_text)
        if dict_match:
            try:
                dict_str = dict_match.group(0)
                # Convert single quotes to double quotes for JSON parsing
                dict_str = dict_str.replace("'", '"')
                parsed_dict = json.loads(dict_str)

                if parsed_dict.get("type") == "tool_calls" and "tool_call" in parsed_dict:
                    tool_data = parsed_dict["tool_call"]
                    LOG.warning(f"Recovered a tool call from a non-standard dict format: {tool_data}")
                    return {"type": "tool_calls", "tool_call": tool_data}
            except json.JSONDecodeError as e:
                LOG.warning(f"Failed to parse dictionary format tool call: {e}")

        LOG.warning("No <tool_call>, <locations>, or implicit tool calls found in dialog output")
        return None
